### PR TITLE
Use different user agent for every request in Google provider

### PR DESCRIPTION
**Pull request by Joozty**
We are still blocked but to avoid being blocked in the future we should change `User-Agent` at least

@business-factory/pythonistas

### CODE REVIEW

**Comment by Joozty** [comment]
@martinvy From my experience, it requires some time to be unblocked. This is just preparation to eliminate the future possibility of blocking by Google.

We were hitting Google quite a lot maybe we should distribute the requests sent to Google in a time. I mean add some sleep time between requests. What do you think?

**Comment by martinvy** [comment]
@Joozty It's difficult to do something when we are blocked at the moment. You can see that I disabled (commented out) Google provider weeks ago so I could try if they unblock us after some time, but while I was doing review for this PR yesterday I saw that we are still blocked so I don't know. I think our IP addresses are blocked.

**Comment by martinvy** [comment]
@miso-belica Well, we can merge it, but it will not be even used, because [Google provider is "disabled"](https://github.com/business-factory/gold-digger/blob/dev/gold_digger/di.py#L69-L70) :/

**Comment by Joozty** [comment]
Ok, I am closing it here as a not useful feature. (The Google provider is going to be removed anyway) :smile:

**Pull request closed without merging**
